### ISSUE TITLE
Idee: Punten omwisselen voor liedjes 

### ISSUE THREAD

**Issue by ManoukK** [Coenmathijssen/real-time-web-1920#2]
Misschien is het leuk dat als users punten verdienen met de spotify game dat zij die punten kunnen verwisselen voor liedjes. Dat 1 punt dan 1 liedje waard is om in de playlist te stoppen

**Comment by Coenmathijssen** [comment]
Goeie! Misschien skip ik wel de punten en noem ik het wel direct songs
